# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 249c254c413714bb310d437802e05e95760f62b29213ceac45db66935858e759b5eb6896dcca4388645e883475c9ee613146308f9588d163d2b1d5275472aed7

test:
  secret_key_base: 5a97f7cdf8ce959977b9055229bdf4af18324a25b45e5f976f81297c1e8f0ac9ecbf3a4b4229807d182d3c3b15a10583cf38e1850c969198182efc2e9ff7ba96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
